apiVersion: apps/v1
kind: Deployment
metadata:
  name: themis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: themis
  template:
    metadata:
      labels:
        name: themis
    spec:
      serviceAccountName: themis
      containers:
        - name: themis
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - themis
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "themis"
